name: dogfinder
description: Dog finder app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  kakao_flutter_sdk_user: ^1.9.7+3
  flutter_naver_login: ^2.1.1
  google_fonts: ^6.3.0
  image_picker: ^1.1.2
  http: ^1.2.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
